### ISSUE TITLE
So, how do you actually install this plugin?

### ISSUE THREAD

**Issue by TheArgentinian** [eliostvs/tomate-indicator-plugin#6]
Installation section links back to the main app page but there's no mention there on how to install plugins. Just links to the plugins.

**Comment by eliostvs** [comment]
Hello, after [configuring the repository](https://github.com/eliostvs/tomate-gtk#installation), install the `tomate-indicator-plugin` package.

**Comment by TheArgentinian** [comment]
> Hello, after [configuring the repository](https://github.com/eliostvs/tomate-gtk#installation), install the `tomate-indicator-plugin` package.

I already installed Tomate. What do you mean by "install the `tomate-indicator-plugin` package.". How?!

**Comment by elioduarte** [comment]
Use your distribution's package manager. In Ubuntu/Debian `sudo apt-get install tomate-indicator-plugin`. In Opensuse `sudo zypper install tomate-indicator-plugin`. Fedora `sudo dnf install tomate-indicator-plugin`. Etc.

**Comment by eliostvs** [comment]
Use your distribution's package manager. In Ubuntu/Debian sudo apt-get install tomate-indicator-plugin. In Opensuse sudo zypper install tomate-indicator-plugin. Fedora sudo dnf install tomate-indicator-plugin. Etc.

**Comment by TheArgentinian** [comment]
> Use your distribution's package manager. In Ubuntu/Debian sudo apt-get install tomate-indicator-plugin. In Opensuse sudo zypper install tomate-indicator-plugin. Fedora sudo dnf install tomate-indicator-plugin. Etc.

got it. thank you!

my only complain now is that there's no pause button :(
